services:
  # A Docker web service
  - type: web
    name: image-caption-api
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false # Indicates this is a secret that needs to be set manually
      - key: OPENROUTER_API_URL
        value: https://openrouter.ai/api/v1/chat/completions
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: DEBUG
        value: false
